Hackathon changes
solana-developers/solana-grants pull request #49
Opened 2022-08-23 14:50 UTC by coszio

## Summer Camp hackathon + last week of MLH

This last week was the most intense of the program, and as a team we managed to get all of the following changes done:

- feat: login component  
- content: replace static content  
- integration: integrate donations
- refactor: cleanup fields in grants-program  
- ui: donation flow
- integration: fetch grants for explore view 
- integration: fetch grants for detail view 
- feat: support author (directly)  
- feat: create grant flow
- ui: markdown editor in create grant 
- ui: used toastify instead of notify in getgrants
- ui: add loading spinner in normal donation popup 
- ui: add default grant image fallback in getgrants

Thanks @RishiDesai17 @yashikajotwani12 @cdhiraj40 @Mayank17M for coming in _clutch_ with these.

2022-08-24 23:59 UTC, jacobcreech requested changes
Few nits. Looking good!

2022-08-24 23:59 UTC, jacobcreech commented on .vscode/launch.json
> +{
Do we need this file? Very specific to local setup

2022-08-24 23:59 UTC, jacobcreech commented on app/src/transactions/index.ts
> +// import * as anchor from "@project-serum/anchor";
Please clean up comments

2022-08-24 23:59 UTC, jacobcreech commented on app/src/transactions/makeDonation.ts
> +// let program: Program<GrantsProgram> = undefined;
Please clean up comments

2022-08-30 15:13 UTC, coszio commented on .vscode/launch.json
> +{
True, I'll add the `.vscode` folder to `.gitignore`

2022-08-30 16:05 UTC, jacobcreech approved these changes

2022-08-30 16:05 UTC, merged